# Generated by Django 4.0.3 on 2022-04-14 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breeze', '0003_profile_alter_item_userid_alter_shoppinglist_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='list_id',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
