# Generated by Django 4.0.3 on 2022-04-22 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breeze', '0005_user_item_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
